[build]
  functions = "netlify/functions"
  command = "npm run generate"  # Runs generate scripts before deployment for static pages & sitemap generation


[dev]
  functions = "netlify/functions"
  framework = "#static"
  port = 3000

[[redirects]]
  from = "/manga/chapter-:chapter"
  to = "/.netlify/functions/renderPage?chapter=:chapter"
  status = 200
  force = true
  

[[redirects]]  
  from = "/assets/*" # server /asset file like /public
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/api/manga"
  to = "/.netlify/functions/getMangaDb"
  status = 200

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/stripe"

[[redirects]]
  from = "/api/addwallet"
  to = "/.netlify/functions/addWallet"
  status = 200


[[redirects]]
  from = "/api/getallwallets"
  to = "/.netlify/functions/getAllWallet"
  status = 200


[[redirects]]  
  from = "/shop" # shortens shop url
  to = "/shop/shop.html"
  status = 200

[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/19390/dystopia-app.site"
  status = 200
  force = true

[functions]
node_bundler = "esbuild"
