[build]
  functions = "netlify/functions"
  command = "npm run generate"  # Runs generate scripts before deployment for static pages & sitemap generation

[[redirects]]
  from = "/manga/chapter-:chapter"
  to = "/.netlify/functions/renderPage?chapter=:chapter"
  status = 200
  force = true
  

[[redirects]]  
  from = "/assets/*" # server /asset file like /public
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/api/manga"
  to = "/.netlify/functions/getMangaDb"
  status = 200


[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/19390/dystopia-app.site"
  status = 200
  force = true

[functions]
node_bundler = "esbuild"
