/**
 * Automates Building Static Pages from Manga Database recursively
 * 
 * Prerenders Static Html pages from the Manga Database
 * This renders each chapter to html rather than rendering pages in realtime using javascript like manga.js
 * The data generated by this script is used by the adsense webcrawler
 * The rendered pages are also fetched by netlifies server and served to users
 *  Device using a netlifiy's api route
 */

// generate-pages.js (Pre-render Static Pages)


import { mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from "url";

// Load the JSON file from the parent directory

const mangaDatabase = JSON.parse(readFileSync("./data/manga.json", "utf-8"));


console.log(`✅ Loaded Database: ${mangaDatabase}`); // Check if the data loads correctly

// Get __dirname equivalent
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const outputDir = join(__dirname, "../dist", "manga");


// Iterate through each manga and its chapters & generate static pages for each object
mangaDatabase.forEach(({ id, title, description, genre, chapters }) => {
    chapters.forEach(({ number, pages }) => {
        const chapterTitle = `Chapter ${number} - ${title}`;
        const keywords = [...genre, title, `Chapter ${number}`].join(", ");
        const firstPage = pages[0] || "default-thumbnail.jpg";

        const html = `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <meta name="description" content="${description}">
                <meta name="keywords" content="${keywords}">
                <title>${chapterTitle}</title>
                <meta property="og:title" content="${chapterTitle}">
                <meta property="og:description" content="${description}">
                <meta property="og:image" content="../../../${firstPage}">
                <meta property="og:type" content="website">
                <style>
                    body { font-family: Arial, sans-serif; text-align: center; }
                    img { max-width: 80%; height: auto; display: block; margin: 10px auto; }
                </style>
            </head>
            <body>
                <h1>${chapterTitle}</h1>
                <p>${description}</p>
                ${pages.map(page => `<img src="../../../${page}" alt="${chapterTitle}">`).join("\n")}
            </body>
            </html>
        `;

        const chapterPath = join(outputDir, id.toString(), `chapter-${number}.html`);
        mkdirSync(dirname(chapterPath), { recursive: true });
        writeFileSync(chapterPath, html, "utf8");

        console.log(`✅ Generated: ${chapterPath}`);
    });
});


console.log("🚀 All static manga pages generated!");
